---
title: "Tidying"
format: html
editor: visual
---

# Tidying shared

## Loading libraries 

```{r}
library(tidyverse)
```

## Importing data 

```{r}
raw_data <- read_csv('EU2014/All waves GENERAL.csv')
```

## Renaming columns

```{r}

# giving columns informative names, translating dutch names
data_renamed <- raw_data |>
rename(
  intnr = INTNR,
  respnr = RESPNR,
  sample = SAMPLE,
  waves = WAVES,
  weight_w1 = GEWICHTA1_w1,
  weight_w2 = GEWICHTA1_w2,
  weight_w3 = GEWICHTA1_w3,
  weight_w4 = GEWICHTA1_w4,
  gender = GSL,
  age = LFT,
  education = OPLA,
  region = NIELSENCBS, 
  family_size = GEZINSGROOTTE,
  pol2012 = POL2012,
  w1_date = w1_DATUM,
  w1_time = w1_TIJD,
  w2_date = w2_DATUM,
  w2_time = w2_TIJD,
  w3_date = w3_DATUM,
  w3_time = w3_TIJD,
  w4_date = w4_DATUM,
  w4_time = w4_TIJD,
) 

# lowercasing column names

colnames(data_renamed) <- tolower(colnames(data_renamed))
```
#### Selecting the variables we need

```{r}

df <- df |>
  select(
    intnr,
    respnr,
    sample,
    gender,
    age,
    waves,
    sample,
    education,
    region,
    family_size,
    w1_date,
    w1_time,
    w2_date,
    w2_time,
    w3_date,
    w3_time,
    w4_date,
    w4_time,
    starts_with("w1_q5"),
    starts_with("w1_q32"),
    starts_with("w1_q34"),
    starts_with("w1_q39"),
    starts_with("w1_q42"),
    starts_with("w1_q61"),
    w1_q65,
    w1_q67,
    w1_q1,
    starts_with("w1_q54"),
    starts_with("w1_q56"),
    starts_with("w1_q68"),
    starts_with("w1_q42"),
    starts_with("w1_q43"),
    starts_with("w1_q10"),
    starts_with("w1_q26"),
    starts_with("w1_q27"),
    starts_with("w1_q12"),
    starts_with("w1_q49"),
    starts_with("w1_q50"),
    starts_with("w1_q51"),
    starts_with("w2_q35"),
    starts_with("w2_q39"),
    starts_with("w2_q2"),
    starts_with("w2_q54"),
    starts_with("w2_q56"),
    starts_with("w2_q43"),
    w2_q27_1,
    w2_q27_2,
    w2_q28_1,
    w2_q28_2,
    w2_q28_6,
    w2_q28_11,
    starts_with("w2_q7"),
    starts_with("w2_q22"),
    starts_with("w2_q23"),
    starts_with("w2_q9"),
    starts_with("w2_q44"),
    starts_with("w2_q45"),
    starts_with("w2_q46"),
    starts_with("w3_q7"),
    starts_with("w3_q3"),
    starts_with("w3_q11"),
    starts_with("w3_q27"),
    starts_with("w3_q29"),
    starts_with("w3_q13"),
    starts_with("w3_q43"),
    starts_with("w3_q44"),
    starts_with("w3_q45"),
    starts_with("w4_q4"),
    starts_with("w4_q13"),
    starts_with("w4_q30"),
    starts_with("w4_q32"),
    starts_with("w4_q15"),
    starts_with("w4_q47"),
    starts_with("w4_q48"),
    starts_with("w4_q49")
  )
```

